# Generated by Django 5.2.15 on 2026-07-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_alter_image_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
            ),
        ),
    ]
